# Generated by Django 4.1.2 on 2022-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafe_contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafe_contrib_profile',
            name='profile_img',
            field=models.FileField(upload_to='rafe_contrib_Pics'),
        ),
    ]
