# Generated by Django 4.1.2 on 2022-12-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafe_contrib', '0003_alter_rafe_contrib_work_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafe_contrib_work',
            name='start',
            field=models.IntegerField(),
        ),
    ]
